[project]
authors = ["EDOUARD DUCHESNAY <edouard.duchesnay@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "nitk"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.0,<3"
scikit-learn = ">=1.7.0,<2"
seaborn = ">=0.13.2,<0.14"
openpyxl = ">=3.1.5,<4"
ipykernel = ">=6.29.5,<7"
nilearn = ">=0.11.1,<0.12"
fsleyes = ">=1.15.0,<2"
shap = ">=0.47.2,<0.48"
